# Multiply the values of the text file in the url by two and export the output to a new file
#url = 'https://www.pythonhow.com/data/sampledata.txt'

import requests
import urllib.request

url = 'http://www.pythonhow.com/data/sampledata.txt'
response = requests.get(url)

print(response.text)    

# O/P: <head><title>Not Acceptable!</title></head><body><h1>Not Acceptable!</h1><p>An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Se
#curity.</p></body></html>

#with open('https://www.pythonhow.com/data/sampledata.txt', 'r') as data_of_file:
#    data = data_of_file.read()
#    print(data)

#with urllib.request.urlopen(url, 'r+') as data_file:
#    data_2 = data_file.read()
#    print(data_2)

#with urllib.request.urlretrieve(url, filename='current_data.txt') as data_input:
#    print('Retrieved the data')

urllib.request.urlretrieve(url, filename='current_data.txt')
data = open('current_data.txt')
data.close()

with open('current_data.txt', 'r+') as retrieved_data:
    data = retrieved_data.read()
    print(data)

    # O/P: 

    #x,y
    #3,5
    #4,9
    #6,10
    #7,11
    #8,12

with open('current_writeback_data.txt', 'w') as writeback_data:
    writeback_data.write('Hello')

    print(type(data))   # O/P: str
    #print(len(data)) # 26

data_list=list(data)

#print(type(data_list))

counter = 1
for i in range(len(data_list)):
    if i < counter:
        if data_list[i].isdigit():
            print(data_list[i])
            int(data_list[i])
            print(type(data_list[i]))
            data_list = ((data_list[i])*2)
            print(data_list)
            counter +=1
        else:
            counter+=1
       # print(data_list[i])


#for i in range(len(data_list)):
#    if isinstance(data_list[i], int):
#        data_list[i] = (data_list[i])*2
#        print(data_list[i])

print(data_list)

#data = ", ".join(data)
#print(data)

#data = data.split(sep='\n')
#print(data)  # O/P: ['x,y', '3,5', '4,9', '6,10', '7,11', '8,12']

## STEP 2 - Now, increment the data retrieved and write a new file

#counter = 0

#while(counter<26):
#    for i in range(len(data)):
#        if i < counter and data[i].isdigit():
#            data[i] = data[i*2]
#            counter +=1
            
#        else:
#            pass
#            counter += 1
    #print(data)



    






















